//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompUniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baskets
    {
        public int id_bi { get; set; }
        public string product { get; set; }
        public int price { get; set; }
        public int id_user { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
